# Generated by Django 4.1 on 2022-08-18 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='fechaDeNacimiento',
        ),
    ]
